name: Data Pipeline

on:
  push:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install pandas

      - name: Run Data Generator
        run: python data_generator/generate_orders.py

      - name: Run Processing
        run: python processing/transform.py