name: Data Pipeline

on:
  push:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install pandas

      - name: Run Data Generator
        run: python data_generator/generate_orders.py

      - name: Run Processing
        run: python processing/transform.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update data" || echo "No changes to commit"
          git push